language: elixir
elixir:
  - '1.10.2'
otp_release:
  - '23.0.1'
notifications:
  email:
    recipients:
      - a@zencoder.com
script:
  - mix test
after_success:
  - "mix compile && mix coveralls.travis"
env:
  - MIX_ENV=test
